filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - "/var/log/tarzan-info.log"
      
# output:
#   logstash:
#     hosts: ["lgs01:5000"]

setup.template.name: "tarzan-info.log"
setup.template.pattern: "tarzan-info.log-*"
setup.template.fields: "fields.yml"
setup.template.overwrite: true
setup.ilm.enabled: false
setup.template.settings:
  index.number_of_shards: 1


output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["http://es01:9200"]
  index: "tarzan-info.log-%{+yyyy.MM.dd}"

name: tarzan-info.log